[package]
license = ["Apache-2.0"]
keywords = ["LiveStorm", "Event", "Webinar"]
org = "ballerinax"
name = "livestorm"
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
